export const movies = [
   {
      id: 70,
      nameRU: 'Здорово и вечно',
      nameEN: 'Machine translate: Healthy and forever',
      director: 'Анна Цирлина, Наталья Чумакова',
      country: 'Россия',
      year: '2014',
      duration: 75,
      description:
         'Фильм «Здорово и вечно» — это первый и единственный фильм, посвященный ранним годам группы «Гражданская оборона», режиссерский дебют Натальи Чумаковой, бас-гитаристки группы и вдовы Егора Летова, и Анны Цирлиной. В основу фильма легли уникальные съемки, сделанные участниками группы, интервью с людьми, принимавшими активное участие в судьбе «Обороны» на начальном этапе, редкие архивные кадры. Режиссеры фильма сделали почти невозможное — собрали внятный и ослепительно живой рассказ о том, как Игорь Летов стал Егором Летовым, фиксирующий происходившее с ним и его кругом с начала 80-х по начало 90-х. «Здорово и вечно» — это не документальный байопик в строгом смысле слова, но скорее успешная попытка поймать мятежный дух времени и людей, которые ломали это время под себя.',
      trailerLink: 'https://www.youtube.com/watch?v=NxJfLA_O7P8',
      created_at: '2020-12-03T16:43:10.490Z',
      updated_at: '2020-12-03T16:43:10.490Z',
      image: {
         id: 70,
         name: 'wyr_139_03',
         alternativeText: '',
         caption: '',
         width: 3112,
         height: 1497,
         formats: {
            thumbnail: {
               hash: 'thumbnail_wyr_139_03_7a244dbd6e',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 245,
               height: 118,
               size: 7.7,
               path: null,
               url: '/uploads/thumbnail_wyr_139_03_7a244dbd6e.jpeg',
            },
            large: {
               hash: 'large_wyr_139_03_7a244dbd6e',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 1000,
               height: 481,
               size: 81.66,
               path: null,
               url: '/uploads/large_wyr_139_03_7a244dbd6e.jpeg',
            },
            medium: {
               hash: 'medium_wyr_139_03_7a244dbd6e',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 750,
               height: 361,
               size: 48.32,
               path: null,
               url: '/uploads/medium_wyr_139_03_7a244dbd6e.jpeg',
            },
            small: {
               hash: 'small_wyr_139_03_7a244dbd6e',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 500,
               height: 241,
               size: 25.28,
               path: null,
               url: '/uploads/small_wyr_139_03_7a244dbd6e.jpeg',
            },
         },
         hash: 'wyr_139_03_7a244dbd6e',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 618.03,
         url: '/uploads/wyr_139_03_7a244dbd6e.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T16:42:25.749Z',
         updated_at: '2020-12-03T16:42:25.749Z',
      },
   },
   {
      id: 71,
      nameRU: 'Зеленые дни',
      nameEN: 'Salad Days',
      director: 'Скотт Крофорд',
      country: 'США',
      year: '2014',
      duration: 90,
      description:
         'История вашингтонского хардкора 80-х и 90-х: от растафари-панков Bad Brains через Minor Threat и до сверхэмоциональных Rites of Spring и Fugazi, о том, как столько честных и лютых музыкантов появилось в одном небольшом городе, известном на весь мир только благодаря Белому дому. Режиссер — журналист, музыкант, графичесий дизайнер, большой фанат жанра в подростковом возрасте — взял за четыре года более ста интервью, а также собрал флаеры, зины, фотографии, кассеты. Да, здесь в основном картинки и говорящие головы — зато какие: от Генри Роллинза про ранние дни и Иэна Маккея про все остальные до сторонних, но неравнодушных наблюдателей Терстона Мура и Дейва Грола; минимум средств — зато максимум громкости и воздействия.',
      trailerLink: 'https://www.youtube.com/watch?v=_cS95rPS5-0',
      created_at: '2020-12-03T16:45:49.178Z',
      updated_at: '2020-12-03T16:45:49.178Z',
      image: {
         id: 71,
         name: 'загруженное',
         alternativeText: '',
         caption: '',
         width: 288,
         height: 175,
         formats: {
            thumbnail: {
               hash: 'thumbnail_zagruzhennoe_b22b6e2887',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 245,
               height: 149,
               size: 7.53,
               path: null,
               url: '/uploads/thumbnail_zagruzhennoe_b22b6e2887.jpeg',
            },
         },
         hash: 'zagruzhennoe_b22b6e2887',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 7.72,
         url: '/uploads/zagruzhennoe_b22b6e2887.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T16:45:14.972Z',
         updated_at: '2020-12-03T16:45:14.972Z',
      },
   },
   {
      id: 72,
      nameRU: 'Из Остина в Бостон',
      nameEN: 'Austin to Boston',
      director: 'Джеймс Маркус',
      country: 'США, Австралия, Великобритания',
      year: '2014',
      duration: 72,
      description:
         "Добраться на машине от Остина, штат Техас, до Бостона, штат Массачусетс, можно за 30 часов. Еще можно растянуть удовольствие — так поступили создатели фильма «Austin to Boston», отправившись в стареньких «Фольксвагенах» в турне по Америке в компании нескольких фолк-музыкантов. Бен Ховард, The Staves, Натаниел Рэтлифф, Bear's Den — даже если какие-то из этих имен вам ничего не говорят, вы можете влюбиться в них после фильма, убедительно доказывающего, что пасечно-сельская музыка нужна далеко не только тем, кто ее поет. Шестидесятые и современность, костры и акустические гитары; разговоры о том, зачем вообще нужны песни; природа и добро, концерты в барах, сараях, на крышах и еще бог знает где; сплошное удовольствие.",
      trailerLink: 'https://www.youtube.com/watch?v=O3MpMb863H0',
      created_at: '2020-12-03T16:48:08.875Z',
      updated_at: '2020-12-03T16:48:08.875Z',
      image: {
         id: 72,
         name: 'images',
         alternativeText: '',
         caption: '',
         width: 300,
         height: 168,
         formats: {
            thumbnail: {
               hash: 'thumbnail_images_d789f0a61a',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 245,
               height: 137,
               size: 9.9,
               path: null,
               url: '/uploads/thumbnail_images_d789f0a61a.jpeg',
            },
         },
         hash: 'images_d789f0a61a',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 12.4,
         url: '/uploads/images_d789f0a61a.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T16:47:03.305Z',
         updated_at: '2020-12-03T16:47:03.305Z',
      },
   },
   {
      id: 73,
      nameRU: 'Только сейчас',
      nameEN: 'All We Have Is Now',
      director: 'Александра Дальстрём',
      country: 'Швеция',
      year: '2014',
      duration: 76,
      description:
         'Vulkano — это три шведки: Сисси, Лиза и Ребекка. Они дружат с детства и не так давно играют дерзкий и одновременно наивный постпанк, но уже удостоились часового документального фильма. Режиссера, а по совместительству диджея и актрису Александру Дальстрём привлекло как то, что девушки хотели просто веселиться и писать музыку, не имея никаких амбиций, так и их драйв, энергичность и умение играть вживую. Дальстрём повсюду следовала за Vulkano с ручной камерой — и в Стокгольме, где происходит большая часть событий, и в Лондоне, и в Лос-Анджелесе. Вот они переодеваются в смешную одежду, вот играют на пианино в пляжных костюмах, вот мило и неумело пишут песни — из всего этого складывается как портрет самой группы, так и картина о доверии, терпении и уважении, без которых в дружбе, как и в творчестве, никуда.',
      trailerLink: 'https://www.youtube.com/watch?v=jVtjHfPTu_Y',
      created_at: '2020-12-03T16:51:33.038Z',
      updated_at: '2020-12-03T16:51:33.038Z',
      image: {
         id: 73,
         name: 'Снимок экрана 2020-12-03 в 19.49.22',
         alternativeText: '',
         caption: '',
         width: 596,
         height: 358,
         formats: {
            thumbnail: {
               hash: 'thumbnail_Snimok_ekrana_2020_12_03_v_19_49_22_913b905856',
               ext: '.png',
               mime: 'image/png',
               width: 245,
               height: 147,
               size: 87.15,
               path: null,
               url: '/uploads/thumbnail_Snimok_ekrana_2020_12_03_v_19_49_22_913b905856.png',
            },
            small: {
               hash: 'small_Snimok_ekrana_2020_12_03_v_19_49_22_913b905856',
               ext: '.png',
               mime: 'image/png',
               width: 500,
               height: 300,
               size: 333.04,
               path: null,
               url: '/uploads/small_Snimok_ekrana_2020_12_03_v_19_49_22_913b905856.png',
            },
         },
         hash: 'Snimok_ekrana_2020_12_03_v_19_49_22_913b905856',
         ext: '.png',
         mime: 'image/png',
         size: 446.87,
         url: '/uploads/Snimok_ekrana_2020_12_03_v_19_49_22_913b905856.png',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T16:50:24.314Z',
         updated_at: '2020-12-03T16:50:24.314Z',
      },
   },
   {
      id: 74,
      nameRU: 'Город Остров',
      nameEN: 'A City Is an Island',
      director: 'Тимоти Джордж Келли',
      country: 'Канада, Великобритания',
      year: '2014',
      duration: 72,
      description:
         '\nМак ДеМарко, Тим Хекер, Патрик Уотсон, Шон Николас Сэвидж, Tonstartssbandht, Колин Стетсон — всех их объединяет не только то, что они прекрасные музыканты, но и общее место происхождения. А также то, что все они засняты в «A City Is an Island», спящими, пишущими песни, репетирующими, дающими концерты и много разговаривающими о столь важном для них Монреале, о его перспективах и проблемах, о том, почему они здесь, а не где-нибудь еще. Монреаль — город, где англоязычный мир пересекается с франкоговорящим. Монреаль — место, в котором благодаря опустевшим складам, лофтам и прочему недорогому жилью сложилось одной из самых мощных творческих сообществ во всем мире. Монреаль — одна из главных мировых музыкальных независимых сцен. Arcade Fire, Граймс, Godspeed You! Black Emperor, кстати, тоже отсюда.',
      trailerLink: 'https://www.youtube.com/watch?v=p0iGMoPglcg',
      created_at: '2020-12-03T16:55:38.088Z',
      updated_at: '2020-12-03T16:55:38.088Z',
      image: {
         id: 75,
         name: 'maxresdefault',
         alternativeText: '',
         caption: '',
         width: 1280,
         height: 720,
         formats: {
            thumbnail: {
               hash: 'thumbnail_maxresdefault_21f787cdf3',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 245,
               height: 138,
               size: 8.57,
               path: null,
               url: '/uploads/thumbnail_maxresdefault_21f787cdf3.jpeg',
            },
            large: {
               hash: 'large_maxresdefault_21f787cdf3',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 1000,
               height: 563,
               size: 72.13,
               path: null,
               url: '/uploads/large_maxresdefault_21f787cdf3.jpeg',
            },
            medium: {
               hash: 'medium_maxresdefault_21f787cdf3',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 750,
               height: 422,
               size: 46.8,
               path: null,
               url: '/uploads/medium_maxresdefault_21f787cdf3.jpeg',
            },
            small: {
               hash: 'small_maxresdefault_21f787cdf3',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 500,
               height: 281,
               size: 26.74,
               path: null,
               url: '/uploads/small_maxresdefault_21f787cdf3.jpeg',
            },
         },
         hash: 'maxresdefault_21f787cdf3',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 64.46,
         url: '/uploads/maxresdefault_21f787cdf3.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T16:52:38.095Z',
         updated_at: '2020-12-03T16:52:38.095Z',
      },
   },
   {
      id: 75,
      nameRU: 'Орион',
      nameEN: 'Orion: The Man Who Would Be King',
      director: 'Джини Финлэй',
      country: 'Великобритания, США',
      year: '2015',
      duration: 88,
      description:
         'Джимми Эллис с детства предпочитал карьеру музыканта конюшне в родной Алабаме, но с 1964 года был толком никому не нужен — пока король и бог рок-н-ролла на горе всей Америке скончался в 1977-м, что послужило причиной как взлета, так и падения Эллиса, известного как Орион. Благодаря маске и тембру голоса Орион-Эллис и Элвис были удивительно похожи; Ориона подписали на тот же лейбл, что и Элвиса, — Sun Records, и слушатели полюбили думать, что Пресли на самом деле до сих пор жив. Фильм о Орионе сняла профессиональный шотландский документалист Джинни Финлэй, автор нескольких документалок, в числе которых «Великого хип-хоп надувательства». Финлэй купила пластинку Ориона за фунт барахолке и, мягко говоря, удивилась сходству двух музыкантов, после чего несколько лет уделила истории человека со славой призрака, поговорив с его близкими, которым он был очень дорог.',
      trailerLink: 'https://www.youtube.com/watch?v=ddqKiHUVlBc',
      created_at: '2020-12-03T16:56:57.356Z',
      updated_at: '2020-12-03T16:56:57.356Z',
      image: {
         id: 76,
         name: 'maxresdefault (1)',
         alternativeText: '',
         caption: '',
         width: 1280,
         height: 720,
         formats: {
            thumbnail: {
               hash: 'thumbnail_maxresdefault_1_0cda104e49',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 245,
               height: 138,
               size: 8.64,
               path: null,
               url: '/uploads/thumbnail_maxresdefault_1_0cda104e49.jpeg',
            },
            large: {
               hash: 'large_maxresdefault_1_0cda104e49',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 1000,
               height: 563,
               size: 86.43,
               path: null,
               url: '/uploads/large_maxresdefault_1_0cda104e49.jpeg',
            },
            medium: {
               hash: 'medium_maxresdefault_1_0cda104e49',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 750,
               height: 422,
               size: 56.36,
               path: null,
               url: '/uploads/medium_maxresdefault_1_0cda104e49.jpeg',
            },
            small: {
               hash: 'small_maxresdefault_1_0cda104e49',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 500,
               height: 281,
               size: 30.31,
               path: null,
               url: '/uploads/small_maxresdefault_1_0cda104e49.jpeg',
            },
         },
         hash: 'maxresdefault_1_0cda104e49',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 105.9,
         url: '/uploads/maxresdefault_1_0cda104e49.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T16:56:07.988Z',
         updated_at: '2020-12-03T16:56:07.988Z',
      },
   },
   {
      id: 76,
      nameRU: ' Возможности безграничны',
      nameEN: 'The Possibilities Are Endless',
      director: 'Джеймс Холл, Эдвард Лавлэйс',
      country: 'Великобритания, США',
      year: '2014',
      duration: 83,
      description:
         'Десять лет назад его хватил удар — он был в коме шесть месяцев и мог выговаривать только слова «да», «нет», «Грейс Максвелл» (имя его жены и менеджера) и «возможности безграничны». Он — Эдвин Коллинс: фронтмен прославленной шотландской постпанк-группы Orange Juice. Несмотря ни на что, он записал несколько сольных альбомов. «Possibilities Are Endless» — это экспериментальный, невероятно красиво снятый документальный фильм: с абстрактными картинами родного для героя Хелмсдейла, трогательными сценами помощи Грейс Коллинсу, который все-таки смог еще появиться на сцене. В равной степени — попытка понять чувства пережившего инсульт, история одной великой любви и высказывание о безграничной силе музыки.',
      trailerLink: 'https://www.youtube.com/watch?v=2pCKC9MioDA',
      created_at: '2020-12-03T16:59:17.595Z',
      updated_at: '2020-12-03T16:59:17.595Z',
      image: {
         id: 77,
         name: 'maxresdefault (2)',
         alternativeText: '',
         caption: '',
         width: 1280,
         height: 720,
         formats: {
            thumbnail: {
               hash: 'thumbnail_maxresdefault_2_3072271808',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 245,
               height: 138,
               size: 11.14,
               path: null,
               url: '/uploads/thumbnail_maxresdefault_2_3072271808.jpeg',
            },
            large: {
               hash: 'large_maxresdefault_2_3072271808',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 1000,
               height: 563,
               size: 207.98,
               path: null,
               url: '/uploads/large_maxresdefault_2_3072271808.jpeg',
            },
            medium: {
               hash: 'medium_maxresdefault_2_3072271808',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 750,
               height: 422,
               size: 119.53,
               path: null,
               url: '/uploads/medium_maxresdefault_2_3072271808.jpeg',
            },
            small: {
               hash: 'small_maxresdefault_2_3072271808',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 500,
               height: 281,
               size: 50.39,
               path: null,
               url: '/uploads/small_maxresdefault_2_3072271808.jpeg',
            },
         },
         hash: 'maxresdefault_2_3072271808',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 327.2,
         url: '/uploads/maxresdefault_2_3072271808.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T16:57:41.958Z',
         updated_at: '2020-12-03T16:57:41.958Z',
      },
   },
   {
      id: 77,
      nameRU: 'Ламберт и Стэмп',
      nameEN: 'Lambert & Stamp',
      director: 'Джеймс Д. Купер',
      country: 'США',
      year: '2014',
      duration: 117,
      description:
         'Свингующий Лондон конца 60-х — начала 70-х. Темные очки, галстуки, оллнайтеры и прочие атрибуты самых первых модов. Группа, написавшая песню «My Generation» и рок-оперу «Tommy». Все это «Lambert & Stamp» — не столько портрет менеджеров группы The Who, вообще-то, сначала мечтавших снять о ней документальный фильм, сколько рассказ о начале самой прекрасной эпохи для гитарной музыки. Как в одном музыкальном коллективе работники офиса и завода уживались со студентом арт-школы и гениальным барабанщиком, чинившим радио? Почему два совершенно разных человека — гей-интеллектуал и брат актера Теренса Стэмпа — решили их продюсировать, хотя считали уродливыми? Насколько огромную роль все они сыграли для своего времени — и что со всеми с ними стало после успеха? Все это заинтересовало отлично дебютировавшего режиссера Джеймса Д.Купера.',
      trailerLink: 'https://www.youtube.com/watch?v=YMaRbIBUvps',
      created_at: '2020-12-03T17:04:21.375Z',
      updated_at: '2020-12-03T17:04:21.375Z',
      image: {
         id: 78,
         name: 'images',
         alternativeText: '',
         caption: '',
         width: 300,
         height: 168,
         formats: {
            thumbnail: {
               hash: 'thumbnail_images_f324307a7f',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 245,
               height: 137,
               size: 8.17,
               path: null,
               url: '/uploads/thumbnail_images_f324307a7f.jpeg',
            },
         },
         hash: 'images_f324307a7f',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 10.05,
         url: '/uploads/images_f324307a7f.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T17:01:26.006Z',
         updated_at: '2020-12-03T17:01:26.006Z',
      },
   },
   {
      id: 78,
      nameRU: 'Ли Скретч Перри: Виденье рая',
      nameEN: 'Lee Scratch Perry’s Vision of Paradise',
      director: 'Фолькер Шанер',
      country: 'Германия, Великобритания, Швейцария, Ямайка, Эфиопия',
      year: '2015',
      duration: 100,
      description:
         'Перед тем как стать человеком, он был рыбой. Сейчас Ли «Скретч» Перри называет себя не иначе как Ноем. Его религия — его сердце; его законы просты — ганджа должна быть свободной, а бога нужно развлекать. Он продюсировал Боба Марли и писал альбом с The Orb, работал с Китом Ричардсом, Beastie Boys и Дэвидом Линчем, научил многих музыкантов пользоваться студией как инструментом и выпустил не один грандиозный даб-альбом. Он разговаривает с коровой и каждое утро вслух приветствует свой компьютер, кружится с раскинутыми руками вокруг Букингемского дворца и напоминает, что все тени одного цвета. «Visions of Paradise» — это документальная сказка по мотивам 13 лет, проведенных немецким режиссером Фолькером Шанером в компании Ли Перри, от Ямайки и Эфиопии до Швейцарии и Лондона. Герой в ней предстает то ли поехавшим дедом, рассуждающим о космических путешествиях, то ли настоящим магом. То есть, вообще говоря, как тем, так и другим.',
      trailerLink: 'https://www.youtube.com/watch?v=9mvjnZAgUNA',
      created_at: '2020-12-03T17:09:04.230Z',
      updated_at: '2020-12-03T17:09:04.230Z',
      image: {
         id: 79,
         name: 'unnamed',
         alternativeText: '',
         caption: '',
         width: 512,
         height: 362,
         formats: {
            thumbnail: {
               hash: 'thumbnail_unnamed_4f99c0fa1e',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 221,
               height: 156,
               size: 12.75,
               path: null,
               url: '/uploads/thumbnail_unnamed_4f99c0fa1e.jpeg',
            },
            small: {
               hash: 'small_unnamed_4f99c0fa1e',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 500,
               height: 354,
               size: 56.29,
               path: null,
               url: '/uploads/small_unnamed_4f99c0fa1e.jpeg',
            },
         },
         hash: 'unnamed_4f99c0fa1e',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 60.22,
         url: '/uploads/unnamed_4f99c0fa1e.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T17:04:50.419Z',
         updated_at: '2020-12-03T17:04:50.419Z',
      },
   },
   {
      id: 79,
      nameRU: 'Любимый небесами',
      nameEN: 'Heaven Adores You',
      director: 'Николас Дилан Росси',
      country: 'США',
      year: '2014',
      duration: 104,
      description:
         '«Я не то чтобы хотел стать знаменитым», — неуверенным, немного ноющим голосом говорит музыкант, для которого номинация его песни на «Оскар» стала нелепым, странным и пугающим событием. В 2003 году он, согласно одной из версий, покончил с собой, воткнув нож себе в грудь. Вразрез с угрюмым началом «Heaven Adores You» — это удивительно духоподъемный, бережно, с обожанием и преданностью сконструированный фильм не об ужасной истории сгорания, не о зависимостях и депрессии, но о прекрасном человеке и музыканте, который жив до сих пор, пусть так только кажется после просмотра. Интервью друзей и причастных, ранее не слышанная музыка и другие раскопки вроде фотографий со школьными друзьями, картины гордов, включая Портленд, где он был знаменит, пока всему миру было наплевать, и Лос-Анджелес, где на бульваре Сансет есть стена в его честь.',
      trailerLink: 'https://www.youtube.com/watch?v=qYy_OBMdcQo',
      created_at: '2020-12-03T17:10:52.837Z',
      updated_at: '2020-12-03T17:10:52.837Z',
      image: {
         id: 80,
         name: 'загруженное',
         alternativeText: '',
         caption: '',
         width: 275,
         height: 183,
         formats: {
            thumbnail: {
               hash: 'thumbnail_zagruzhennoe_a32e347316',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 234,
               height: 156,
               size: 9.22,
               path: null,
               url: '/uploads/thumbnail_zagruzhennoe_a32e347316.jpeg',
            },
         },
         hash: 'zagruzhennoe_a32e347316',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 9.76,
         url: '/uploads/zagruzhennoe_a32e347316.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T17:09:56.363Z',
         updated_at: '2020-12-03T17:09:56.363Z',
      },
   },
   // {
   //    id: 80,
   //    nameRU: 'От станции к станции',
   //    nameEN: 'Station to Station',
   //    director: 'Даг Эйткен',
   //    country: 'США',
   //    year: '2015',
   //    duration: 71,
   //    description:
   //       'Бродячий оркестр из музыкантов, художников, архитекторов, фотографов и танцоров едет на поезде из Нью-Йорка в Окленд.\n\n24 дня, 10 остановок, два океана- один железнодорожный путь калифорниец Дуг Айткен превратил в 61 мини-фильм. В каждом из них заснят как поезд, очень красиво светящийся светодиодами, так и непосредственный момент создания того или иного произведения, будь то концерт Бека с госпельным хором, рисующая машина Олафура Элиассона или негромко поющий Эриэл Пинк в колготках. Все они кратко рассказывают, что думают о путешествиях, жизни, индустрии и вообще своей работе, попутно описывая собственные творческие методы.\n\nЗритель выступает то как собеседник этих грандиозных личностей, то как пассажир, который смотрит на Америку из окна, то как сторонний наблюдатель этой конструкции, несущейся куда-то прямо в вечность.',
   //    trailerLink: 'https://www.youtube.com/watch?v=FNWN0N0b1qc',
   //    created_at: '2020-12-03T17:12:50.705Z',
   //    updated_at: '2020-12-03T17:12:50.705Z',
   //    image: {
   //       id: 81,
   //       name: 'maxresdefault',
   //       alternativeText: '',
   //       caption: '',
   //       width: 1280,
   //       height: 720,
   //       formats: {
   //          thumbnail: {
   //             hash: 'thumbnail_maxresdefault_164e1c974c',
   //             ext: '.jpeg',
   //             mime: 'image/jpeg',
   //             width: 245,
   //             height: 138,
   //             size: 7.36,
   //             path: null,
   //             url: '/uploads/thumbnail_maxresdefault_164e1c974c.jpeg',
   //          },
   //          large: {
   //             hash: 'large_maxresdefault_164e1c974c',
   //             ext: '.jpeg',
   //             mime: 'image/jpeg',
   //             width: 1000,
   //             height: 563,
   //             size: 63.81,
   //             path: null,
   //             url: '/uploads/large_maxresdefault_164e1c974c.jpeg',
   //          },
   //          medium: {
   //             hash: 'medium_maxresdefault_164e1c974c',
   //             ext: '.jpeg',
   //             mime: 'image/jpeg',
   //             width: 750,
   //             height: 422,
   //             size: 41.32,
   //             path: null,
   //             url: '/uploads/medium_maxresdefault_164e1c974c.jpeg',
   //          },
   //          small: {
   //             hash: 'small_maxresdefault_164e1c974c',
   //             ext: '.jpeg',
   //             mime: 'image/jpeg',
   //             width: 500,
   //             height: 281,
   //             size: 22.08,
   //             path: null,
   //             url: '/uploads/small_maxresdefault_164e1c974c.jpeg',
   //          },
   //       },
   //       hash: 'maxresdefault_164e1c974c',
   //       ext: '.jpeg',
   //       mime: 'image/jpeg',
   //       size: 87.68,
   //       url: '/uploads/maxresdefault_164e1c974c.jpeg',
   //       provider: 'local',
   //       provider_metadata: null,
   //       created_at: '2020-12-03T17:12:02.905Z',
   //       updated_at: '2020-12-03T17:12:02.905Z',
   //    },
   // },
   {
      id: 81,
      nameRU: 'Берроуз',
      nameEN: 'Burroughs: The Movie',
      director: 'Ховард Брукнер',
      country: 'США',
      year: '1983',
      duration: 86,
      description:
         'Первый и единственный длинный документальный фильм о великом контркультурном писателе, который с большим удовольствием становится под прицел видеокамеры. Режиссер Говард Брукнер начал работать над «Burroughs» в 1978-м как над выпускной работой из Нью-Йоркского университета. Закончил в 1983-м, проведя много времени и с самим Берроузом, и с его друзьями и последователями. В кадре появляются Аллен Гинзберг и Патти Смит, оператор — Том Дичилло, звук вообще записан товарищем Брукнера по имени Джим Джармуш. Брукнер умер в 1989-м — к столетию со дня рождения Берроуза, в 2014-м, всего несколько раз показанный фильм был доделан и перевыпущен племянником режиссера. От США до Северной Африки, от чтения отрывков из «Голого завтрака» до воспоминаний о мололодости, от бесценных монологов до живого и порой очень смешного общения героя с другими людьми — обо всем этом с бесконечной демонической привлекательностью.',
      trailerLink: 'https://www.youtube.com/watch?v=5m_1N_phcjo',
      created_at: '2020-12-03T18:02:11.621Z',
      updated_at: '2020-12-03T18:02:11.621Z',
      image: {
         id: 82,
         name: 'b80915f7-d774-4536-9e79-450578a40ad4-9131a274',
         alternativeText: '',
         caption: '',
         width: 640,
         height: 360,
         formats: {
            thumbnail: {
               hash: 'thumbnail_b80915f7_d774_4536_9e79_450578a40ad4_9131a274_04cd1fb520',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 245,
               height: 138,
               size: 5.38,
               path: null,
               url: '/uploads/thumbnail_b80915f7_d774_4536_9e79_450578a40ad4_9131a274_04cd1fb520.jpeg',
            },
            small: {
               hash: 'small_b80915f7_d774_4536_9e79_450578a40ad4_9131a274_04cd1fb520',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 500,
               height: 281,
               size: 17.46,
               path: null,
               url: '/uploads/small_b80915f7_d774_4536_9e79_450578a40ad4_9131a274_04cd1fb520.jpeg',
            },
         },
         hash: 'b80915f7_d774_4536_9e79_450578a40ad4_9131a274_04cd1fb520',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 25.39,
         url: '/uploads/b80915f7_d774_4536_9e79_450578a40ad4_9131a274_04cd1fb520.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T17:58:43.203Z',
         updated_at: '2020-12-03T17:58:43.203Z',
      },
   },
   {
      id: 82,
      nameRU: 'Бэнкси уделывает Нью-Йорк',
      nameEN: 'Banksy Does New York',
      director: ' Крис Мукарбел',
      country: 'США',
      year: '2014',
      duration: 79,
      description:
         'В октябре 2013-го Бэнкси решил устроить, пожалуй, самую масштабную свою выставку — и за месяц прошелся по Нью-Йорку, точно ураган. Каждый день он — разумеется, анонимно — выходил на улицу, чтобы превратить очередной клочок стены или закоулок квартала, до того не видавшего паблик-арта, в масштабную арт-инсталляцию, тем самым заставляя охотиться за собой одновременно толпы местных жителей и полицию. Все это дало эффект, сам по себе являющийся лучшим комментарием к современному искусству: люди не только снимали все происходящее на мобильный телефон, выкладывали в инстаграм и проставляли хэштеги, тем самым становясь частью экспозиции, — но и похищали работы, брали деньги с желающих их сфотографировать и даже вырывали с корнем, чтобы потом продать в какую-нибудь престижную галерею современного искусства.',
      trailerLink: 'https://www.youtube.com/watch?v=BMnoLW1RZ8I',
      created_at: '2020-12-03T18:04:53.958Z',
      updated_at: '2020-12-03T18:04:53.958Z',
      image: {
         id: 83,
         name: '12032-770x433',
         alternativeText: '',
         caption: '',
         width: 770,
         height: 433,
         formats: {
            thumbnail: {
               hash: 'thumbnail_12032_770x433_74026cdeb6',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 245,
               height: 138,
               size: 7.85,
               path: null,
               url: '/uploads/thumbnail_12032_770x433_74026cdeb6.jpeg',
            },
            medium: {
               hash: 'medium_12032_770x433_74026cdeb6',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 750,
               height: 422,
               size: 61.29,
               path: null,
               url: '/uploads/medium_12032_770x433_74026cdeb6.jpeg',
            },
            small: {
               hash: 'small_12032_770x433_74026cdeb6',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 500,
               height: 281,
               size: 29.49,
               path: null,
               url: '/uploads/small_12032_770x433_74026cdeb6.jpeg',
            },
         },
         hash: '12032_770x433_74026cdeb6',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 66.03,
         url: '/uploads/12032_770x433_74026cdeb6.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T18:04:02.124Z',
         updated_at: '2020-12-03T18:04:02.124Z',
      },
   },
];
