export const savedMovies = [
   {
      id: 73,
      nameRU: 'Только сейчас',
      nameEN: 'All We Have Is Now',
      director: 'Александра Дальстрём',
      country: 'Швеция',
      year: '2014',
      duration: 76,
      description:
         'Vulkano — это три шведки: Сисси, Лиза и Ребекка. Они дружат с детства и не так давно играют дерзкий и одновременно наивный постпанк, но уже удостоились часового документального фильма. Режиссера, а по совместительству диджея и актрису Александру Дальстрём привлекло как то, что девушки хотели просто веселиться и писать музыку, не имея никаких амбиций, так и их драйв, энергичность и умение играть вживую. Дальстрём повсюду следовала за Vulkano с ручной камерой — и в Стокгольме, где происходит большая часть событий, и в Лондоне, и в Лос-Анджелесе. Вот они переодеваются в смешную одежду, вот играют на пианино в пляжных костюмах, вот мило и неумело пишут песни — из всего этого складывается как портрет самой группы, так и картина о доверии, терпении и уважении, без которых в дружбе, как и в творчестве, никуда.',
      trailerLink: 'https://www.youtube.com/watch?v=jVtjHfPTu_Y',
      created_at: '2020-12-03T16:51:33.038Z',
      updated_at: '2020-12-03T16:51:33.038Z',
      image: {
         id: 73,
         name: 'Снимок экрана 2020-12-03 в 19.49.22',
         alternativeText: '',
         caption: '',
         width: 596,
         height: 358,
         formats: {
            thumbnail: {
               hash: 'thumbnail_Snimok_ekrana_2020_12_03_v_19_49_22_913b905856',
               ext: '.png',
               mime: 'image/png',
               width: 245,
               height: 147,
               size: 87.15,
               path: null,
               url: '/uploads/thumbnail_Snimok_ekrana_2020_12_03_v_19_49_22_913b905856.png',
            },
            small: {
               hash: 'small_Snimok_ekrana_2020_12_03_v_19_49_22_913b905856',
               ext: '.png',
               mime: 'image/png',
               width: 500,
               height: 300,
               size: 333.04,
               path: null,
               url: '/uploads/small_Snimok_ekrana_2020_12_03_v_19_49_22_913b905856.png',
            },
         },
         hash: 'Snimok_ekrana_2020_12_03_v_19_49_22_913b905856',
         ext: '.png',
         mime: 'image/png',
         size: 446.87,
         url: '/uploads/Snimok_ekrana_2020_12_03_v_19_49_22_913b905856.png',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T16:50:24.314Z',
         updated_at: '2020-12-03T16:50:24.314Z',
      },
   },
   {
      id: 77,
      nameRU: 'Ламберт и Стэмп',
      nameEN: 'Lambert & Stamp',
      director: 'Джеймс Д. Купер',
      country: 'США',
      year: '2014',
      duration: 117,
      description:
         'Свингующий Лондон конца 60-х — начала 70-х. Темные очки, галстуки, оллнайтеры и прочие атрибуты самых первых модов. Группа, написавшая песню «My Generation» и рок-оперу «Tommy». Все это «Lambert & Stamp» — не столько портрет менеджеров группы The Who, вообще-то, сначала мечтавших снять о ней документальный фильм, сколько рассказ о начале самой прекрасной эпохи для гитарной музыки. Как в одном музыкальном коллективе работники офиса и завода уживались со студентом арт-школы и гениальным барабанщиком, чинившим радио? Почему два совершенно разных человека — гей-интеллектуал и брат актера Теренса Стэмпа — решили их продюсировать, хотя считали уродливыми? Насколько огромную роль все они сыграли для своего времени — и что со всеми с ними стало после успеха? Все это заинтересовало отлично дебютировавшего режиссера Джеймса Д.Купера.',
      trailerLink: 'https://www.youtube.com/watch?v=YMaRbIBUvps',
      created_at: '2020-12-03T17:04:21.375Z',
      updated_at: '2020-12-03T17:04:21.375Z',
      image: {
         id: 78,
         name: 'images',
         alternativeText: '',
         caption: '',
         width: 300,
         height: 168,
         formats: {
            thumbnail: {
               hash: 'thumbnail_images_f324307a7f',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 245,
               height: 137,
               size: 8.17,
               path: null,
               url: '/uploads/thumbnail_images_f324307a7f.jpeg',
            },
         },
         hash: 'images_f324307a7f',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 10.05,
         url: '/uploads/images_f324307a7f.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T17:01:26.006Z',
         updated_at: '2020-12-03T17:01:26.006Z',
      },
   },
   {
      id: 78,
      nameRU: 'Ли Скретч Перри: Виденье рая',
      nameEN: 'Lee Scratch Perry’s Vision of Paradise',
      director: 'Фолькер Шанер',
      country: 'Германия, Великобритания, Швейцария, Ямайка, Эфиопия',
      year: '2015',
      duration: 100,
      description:
         'Перед тем как стать человеком, он был рыбой. Сейчас Ли «Скретч» Перри называет себя не иначе как Ноем. Его религия — его сердце; его законы просты — ганджа должна быть свободной, а бога нужно развлекать. Он продюсировал Боба Марли и писал альбом с The Orb, работал с Китом Ричардсом, Beastie Boys и Дэвидом Линчем, научил многих музыкантов пользоваться студией как инструментом и выпустил не один грандиозный даб-альбом. Он разговаривает с коровой и каждое утро вслух приветствует свой компьютер, кружится с раскинутыми руками вокруг Букингемского дворца и напоминает, что все тени одного цвета. «Visions of Paradise» — это документальная сказка по мотивам 13 лет, проведенных немецким режиссером Фолькером Шанером в компании Ли Перри, от Ямайки и Эфиопии до Швейцарии и Лондона. Герой в ней предстает то ли поехавшим дедом, рассуждающим о космических путешествиях, то ли настоящим магом. То есть, вообще говоря, как тем, так и другим.',
      trailerLink: 'https://www.youtube.com/watch?v=9mvjnZAgUNA',
      created_at: '2020-12-03T17:09:04.230Z',
      updated_at: '2020-12-03T17:09:04.230Z',
      image: {
         id: 79,
         name: 'unnamed',
         alternativeText: '',
         caption: '',
         width: 512,
         height: 362,
         formats: {
            thumbnail: {
               hash: 'thumbnail_unnamed_4f99c0fa1e',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 221,
               height: 156,
               size: 12.75,
               path: null,
               url: '/uploads/thumbnail_unnamed_4f99c0fa1e.jpeg',
            },
            small: {
               hash: 'small_unnamed_4f99c0fa1e',
               ext: '.jpeg',
               mime: 'image/jpeg',
               width: 500,
               height: 354,
               size: 56.29,
               path: null,
               url: '/uploads/small_unnamed_4f99c0fa1e.jpeg',
            },
         },
         hash: 'unnamed_4f99c0fa1e',
         ext: '.jpeg',
         mime: 'image/jpeg',
         size: 60.22,
         url: '/uploads/unnamed_4f99c0fa1e.jpeg',
         provider: 'local',
         provider_metadata: null,
         created_at: '2020-12-03T17:04:50.419Z',
         updated_at: '2020-12-03T17:04:50.419Z',
      },
   },
];
